# Site settings
title: Seungyub Han
email: hansy1124@gmail.com
description: >
 Department of Political Science
 Bunche Hall 
 Los Angeles, CA 90095
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://hansy1124.github.io/" # the base hostname & protocol for your site
github_username:  doeun-kim
encoding: UTF-8
# Build settings
markdown: kramdown
